/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import Model.Pasien;
import DAO.PasienDAO;
import DAO.RekamMedisDAO;
import Util.DbConnection;
import java.awt.Desktop;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.sql.Timestamp;
import java.util.Date;
import Gui.RekamMedis;


import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;



/**
 *
 * @author asus
 */
public class DataPasien extends javax.swing.JFrame {

    /**
     * 
     */
    public DataPasien() {
        initComponents();
        loadTable();
        
    }
    
    private void loadTable() {
    DefaultTableModel model;
    String[] kolom = {"ID", "Nama", "Tanggal Lahir", "Jenis Kelamin", "Alamat", "No Telepon", "Email"};
    model = new DefaultTableModel(null, kolom);
    List<Pasien> list = new PasienDAO().getAllPasien();

    for (Pasien p : list) {
        model.addRow(new Object[]{
            p.getId(), p.getNama(),
            new SimpleDateFormat("yyyy-MM-dd").format(p.getTanggalLahir()),
            p.getJenisKelamin(), p.getAlamat(),
            p.getNoTelepon(), p.getEmail()
        });
    }
    DaftarPasienTbl.setModel(model);
}

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MENU = new javax.swing.JPanel();
        farmasi = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dashboard = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pasien = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dokter = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        nav = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        DataPasienlb = new javax.swing.JLabel();
        BuatRm = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DaftarPasienTbl = new javax.swing.JTable();
        CetakRekambtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 500));

        MENU.setBackground(new java.awt.Color(127, 85, 177));
        MENU.setPreferredSize(new java.awt.Dimension(270, 450));
        MENU.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        farmasi.setBackground(new java.awt.Color(78, 48, 115));
        farmasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                farmasiMouseClicked(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-pharmacy-shop-24.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(25, 25));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Farmasi");

        javax.swing.GroupLayout farmasiLayout = new javax.swing.GroupLayout(farmasi);
        farmasi.setLayout(farmasiLayout);
        farmasiLayout.setHorizontalGroup(
            farmasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(farmasiLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(122, 122, 122))
        );
        farmasiLayout.setVerticalGroup(
            farmasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(farmasiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(farmasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(150, 150, 150))
        );

        MENU.add(farmasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 270, 40));

        dashboard.setBackground(new java.awt.Color(78, 48, 115));
        dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardMouseClicked(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-home-24.png"))); // NOI18N
        jLabel5.setPreferredSize(new java.awt.Dimension(25, 25));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Dashboard");

        javax.swing.GroupLayout dashboardLayout = new javax.swing.GroupLayout(dashboard);
        dashboard.setLayout(dashboardLayout);
        dashboardLayout.setHorizontalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(122, 122, 122))
        );
        dashboardLayout.setVerticalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(150, 150, 150))
        );

        MENU.add(dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 270, 40));

        pasien.setBackground(new java.awt.Color(155, 126, 189));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-patient-24.png"))); // NOI18N
        jLabel7.setPreferredSize(new java.awt.Dimension(25, 25));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Pasien");

        javax.swing.GroupLayout pasienLayout = new javax.swing.GroupLayout(pasien);
        pasien.setLayout(pasienLayout);
        pasienLayout.setHorizontalGroup(
            pasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pasienLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(122, 122, 122))
        );
        pasienLayout.setVerticalGroup(
            pasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pasienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(150, 150, 150))
        );

        MENU.add(pasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 270, 40));

        dokter.setBackground(new java.awt.Color(78, 48, 115));
        dokter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dokterMouseClicked(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-doctor-24.png"))); // NOI18N
        jLabel9.setPreferredSize(new java.awt.Dimension(25, 25));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Dokter");

        javax.swing.GroupLayout dokterLayout = new javax.swing.GroupLayout(dokter);
        dokter.setLayout(dokterLayout);
        dokterLayout.setHorizontalGroup(
            dokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dokterLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(122, 122, 122))
        );
        dokterLayout.setVerticalGroup(
            dokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dokterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(150, 150, 150))
        );

        MENU.add(dokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 270, 40));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Klinik Kartika Surabaya");
        MENU.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));
        MENU.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 82, 270, 10));

        getContentPane().add(MENU, java.awt.BorderLayout.LINE_START);

        nav.setBackground(new java.awt.Color(255, 255, 255));
        nav.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(244, 155, 171));
        header.setAlignmentX(6.0F);
        header.setAlignmentY(6.0F);

        DataPasienlb.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        DataPasienlb.setForeground(new java.awt.Color(255, 255, 255));
        DataPasienlb.setText("Data Pasien");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(DataPasienlb)
                .addContainerGap(455, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(DataPasienlb)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        nav.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        BuatRm.setBackground(new java.awt.Color(127, 85, 177));
        BuatRm.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Daftar Pasien", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        DaftarPasienTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nomor Rekam Medis", "Nama Lengkap", "Tanggal Lahir", "Jenis Kelamin", "Alamat", "No Telepon", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        DaftarPasienTbl.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(DaftarPasienTbl);
        if (DaftarPasienTbl.getColumnModel().getColumnCount() > 0) {
            DaftarPasienTbl.getColumnModel().getColumn(0).setResizable(false);
            DaftarPasienTbl.getColumnModel().getColumn(1).setResizable(false);
            DaftarPasienTbl.getColumnModel().getColumn(2).setResizable(false);
            DaftarPasienTbl.getColumnModel().getColumn(3).setResizable(false);
            DaftarPasienTbl.getColumnModel().getColumn(4).setResizable(false);
            DaftarPasienTbl.getColumnModel().getColumn(5).setResizable(false);
            DaftarPasienTbl.getColumnModel().getColumn(6).setResizable(false);
            DaftarPasienTbl.getColumnModel().getColumn(7).setResizable(false);
        }

        CetakRekambtn.setText("Buat Rekam Medis");
        CetakRekambtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CetakRekambtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BuatRmLayout = new javax.swing.GroupLayout(BuatRm);
        BuatRm.setLayout(BuatRmLayout);
        BuatRmLayout.setHorizontalGroup(
            BuatRmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuatRmLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BuatRmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BuatRmLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(CetakRekambtn)))
                .addContainerGap())
        );
        BuatRmLayout.setVerticalGroup(
            BuatRmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuatRmLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(CetakRekambtn)
                .addContainerGap())
        );

        nav.add(BuatRm, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 610, 370));

        getContentPane().add(nav, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseClicked
        // TODO add your handling code here:
        new Dashboard().setVisible(true);
        dispose();
    }//GEN-LAST:event_dashboardMouseClicked

    private void dokterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dokterMouseClicked
        // TODO add your handling code here:
        new Dokter().setVisible(true);
        dispose();
    }//GEN-LAST:event_dokterMouseClicked

    private void farmasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_farmasiMouseClicked
        // TODO add your handling code here:
        new Farmasi().setVisible(true);
        dispose();
    }//GEN-LAST:event_farmasiMouseClicked

    private void CetakRekambtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CetakRekambtnActionPerformed
        // TODO add your handling code here:
      int selectedRow = DaftarPasienTbl.getSelectedRow();
        if (selectedRow != -1) {
            // Ambil data dari tabel
            String nama = DaftarPasienTbl.getValueAt(selectedRow, 1).toString();
            String tanggalLahir = DaftarPasienTbl.getValueAt(selectedRow, 2).toString();
            String jenisKelamin = DaftarPasienTbl.getValueAt(selectedRow, 3).toString();
            String alamat = DaftarPasienTbl.getValueAt(selectedRow, 4).toString();
            String telepon = DaftarPasienTbl.getValueAt(selectedRow, 5).toString();
            String email = DaftarPasienTbl.getValueAt(selectedRow, 6).toString();

            // Buka RekamMedis dan teruskan data
            RekamMedis rekam = new RekamMedis();
            rekam.setDataPasien(nama, tanggalLahir, jenisKelamin, alamat, telepon, email);
            rekam.setVisible(true);

            // Tutup form ini jika perlu
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Pilih pasien terlebih dahulu!");
        }
             
    }//GEN-LAST:event_CetakRekambtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataPasien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BuatRm;
    private javax.swing.JButton CetakRekambtn;
    private javax.swing.JTable DaftarPasienTbl;
    private javax.swing.JLabel DataPasienlb;
    private javax.swing.JPanel MENU;
    private javax.swing.JPanel dashboard;
    private javax.swing.JPanel dokter;
    private javax.swing.JPanel farmasi;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel nav;
    private javax.swing.JPanel pasien;
    // End of variables declaration//GEN-END:variables
}
