/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import java.sql.*;
import javax.swing.*;
import Gui.Dashboard;
import DAO.AdminDAO;
import Model.Admin;

/**
 *
 * @author asus
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JPanel();
        logolbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        login = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        loginlbl = new javax.swing.JLabel();
        usernamelbl = new javax.swing.JLabel();
        Usernametxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        passwordtxt = new javax.swing.JPasswordField();
        Loginbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 500));
        getContentPane().setLayout(new java.awt.GridLayout(0, 2));

        logo.setBackground(new java.awt.Color(255, 255, 255));
        logo.setPreferredSize(new java.awt.Dimension(0, 500));
        logo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logolbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logolbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        logolbl.setMaximumSize(new java.awt.Dimension(200, 200));
        logolbl.setMinimumSize(new java.awt.Dimension(200, 200));
        logolbl.setPreferredSize(new java.awt.Dimension(200, 200));
        logo.add(logolbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 270, 250));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(127, 85, 177));
        jLabel3.setText("KLINIK KARTIKA SURABAYA");
        logo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(127, 85, 177));
        jLabel2.setText("Jl. Ngagel Jaya Utara No.2A, Pucang Sewu, Kec. Gubeng ");
        logo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, 20));

        getContentPane().add(logo);

        login.setBackground(new java.awt.Color(127, 85, 177));
        login.setPreferredSize(new java.awt.Dimension(500, 500));
        login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(250, 250));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginlbl.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        loginlbl.setForeground(new java.awt.Color(127, 85, 177));
        loginlbl.setText("LOG IN");
        jPanel3.add(loginlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        usernamelbl.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        usernamelbl.setForeground(new java.awt.Color(127, 85, 177));
        usernamelbl.setText("Username");
        jPanel3.add(usernamelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 64, 68, -1));
        jPanel3.add(Usernametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 89, 250, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(127, 85, 177));
        jLabel6.setText("Password");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 127, 63, -1));
        jPanel3.add(passwordtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 152, 250, -1));

        Loginbtn.setBackground(new java.awt.Color(127, 85, 177));
        Loginbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Loginbtn.setForeground(new java.awt.Color(255, 255, 255));
        Loginbtn.setText("LOG IN");
        Loginbtn.setBorderPainted(false);
        Loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginbtnActionPerformed(evt);
            }
        });
        jPanel3.add(Loginbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 190, 250, -1));

        login.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 300, -1));

        getContentPane().add(login);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LoginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginbtnActionPerformed
        // TODO add your handling code here:
    String username = Usernametxt.getText();
    String password = new String(passwordtxt.getPassword());

    AdminDAO dao = new AdminDAO();
    Admin admin = dao.login(username, password);

    if (admin != null) {
        JOptionPane.showMessageDialog(this, "Login berhasil!");

        // Masuk ke dashboard
        Dashboard dashboard = new Dashboard();
        dashboard.setVisible(true);
        this.dispose(); // Tutup halaman login
    } else {
        JOptionPane.showMessageDialog(this, "Username atau password salah!", "Login Gagal", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_LoginbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Loginbtn;
    private javax.swing.JTextField Usernametxt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel login;
    private javax.swing.JLabel loginlbl;
    private javax.swing.JPanel logo;
    private javax.swing.JLabel logolbl;
    private javax.swing.JPasswordField passwordtxt;
    private javax.swing.JLabel usernamelbl;
    // End of variables declaration//GEN-END:variables
}
