/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import DAO.RekamMedisDAO;
import Model.Pasien;
import Util.DbConnection;
import com.openhtmltopdf.pdfboxout.PdfRendererBuilder;
import java.io.*;
import java.nio.file.*;
import java.text.SimpleDateFormat;
import java.util.Date;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.FileOutputStream;
import java.nio.charset.StandardCharsets;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.border.TitledBorder;


/**
 *
 * @author Lenovo
 */
public class RekamMedis extends javax.swing.JFrame {

    /**
     * Creates new form RekamMedis
     */
    
    
//    private int idPasien;
    
    public RekamMedis() {
        initComponents();
//        this.idPasien = idPasien;
        
    }

    private void exportToPDF() {
       try {
        // Lokasi template
        String templatePath = "src/Util/RekamMedis.html";
        String html = new String(Files.readAllBytes(Paths.get(templatePath)), StandardCharsets.UTF_8);
      


        // Ganti placeholder HTML dengan isi form
        html = html.replace("{{nama_pasien}}", NamaPasienField.getText());
        html = html.replace("{{tanggal_lahir}}", TglLahirField.getText());
        html = html.replace("{{jenis_kelamin}}", JenisKelaminField.getText());
        html = html.replace("{{alamat}}", AlamatField.getText());
        html = html.replace("{{no_telepon}}", TelpField.getText());
        html = html.replace("{{email}}", EmailField.getText());
        html = html.replace("{{waktu_kunjungan}}", WaktuField.getText());
        html = html.replace("{{jenis_kunjungan}}", Combox.getSelectedItem().toString());
        html = html.replace("{{diagnosis}}", DiagnosisField.getText());
        html = html.replace("{{tindakan}}", TindakanField.getText());
        html = html.replace("{{obat}}", ObatField.getText());
        html = html.replace("{{catatan}}", CatatanField.getText());
        html = html.replace("{{dokter}}", DokterBox.getSelectedItem().toString());
        html = html.replace("{{kontrol_ulang}}", JadwalFild.getText());
        html = html.replace("{{printed}}", new SimpleDateFormat("dd-MM-yyyy HH:mm").format(new Date()));


        // Lokasi simpan PDF
        String namaFile = "RekamMedis_" + NamaPasienField.getText().replaceAll("\\s+", "_") + ".pdf";
        File outputFile = new File(namaFile);

        // Render PDF
        try (OutputStream os = new FileOutputStream(outputFile)) {
            PdfRendererBuilder builder = new PdfRendererBuilder();
            builder.useFastMode();
            builder.withHtmlContent(html, new File(templatePath).toURI().toString());
            builder.toStream(os);
            builder.run();
        }

        JOptionPane.showMessageDialog(this, "PDF berhasil disimpan:\n" + outputFile.getAbsolutePath());
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Gagal mencetak PDF: " + e.getMessage());
    }
    }
    
    public void setDataPasien(String nama, String tglLahir, String jk, String alamat, String telepon, String email) {
    NamaPasienField.setText(nama);
    TglLahirField.setText(tglLahir);
    JenisKelaminField.setText(jk);
    AlamatField.setText(alamat);
    TelpField.setText(telepon);
    EmailField.setText(email);
}
    private void clearForm() {
    DiagnosisField.setText("");
    TindakanField.setText("");
    ObatField.setText("");
    CatatanField.setText("");
    JadwalFild.setText("");
    WaktuField.setText("");
    Combox.setSelectedIndex(0);
}




    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MENU = new javax.swing.JPanel();
        farmasi = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dashboard = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pasien = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dokter = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Content = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Mid = new javax.swing.JPanel();
        Idtxt = new javax.swing.JLabel();
        NamaPasienField = new javax.swing.JTextField();
        Pasientxt = new javax.swing.JLabel();
        TglLahirField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        JenisKelaminField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        AlamatField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        TelpField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        EmailField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        WaktuField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        Combox = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        DiagnosisField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        TindakanField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        ObatField = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        CatatanField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        DokterBox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        JadwalFild = new javax.swing.JTextField();
        Foot = new javax.swing.JPanel();
        Simpanbtn = new javax.swing.JButton();
        ExportPdf = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MENU.setBackground(new java.awt.Color(127, 85, 177));
        MENU.setPreferredSize(new java.awt.Dimension(270, 450));
        MENU.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        farmasi.setBackground(new java.awt.Color(78, 48, 115));
        farmasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                farmasiMouseClicked(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-pharmacy-shop-24.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(25, 25));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Farmasi");

        javax.swing.GroupLayout farmasiLayout = new javax.swing.GroupLayout(farmasi);
        farmasi.setLayout(farmasiLayout);
        farmasiLayout.setHorizontalGroup(
            farmasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(farmasiLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(122, 122, 122))
        );
        farmasiLayout.setVerticalGroup(
            farmasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(farmasiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(farmasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(150, 150, 150))
        );

        MENU.add(farmasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 270, 40));

        dashboard.setBackground(new java.awt.Color(78, 48, 115));
        dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardMouseClicked(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-home-24.png"))); // NOI18N
        jLabel5.setPreferredSize(new java.awt.Dimension(25, 25));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Dashboard");

        javax.swing.GroupLayout dashboardLayout = new javax.swing.GroupLayout(dashboard);
        dashboard.setLayout(dashboardLayout);
        dashboardLayout.setHorizontalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(122, 122, 122))
        );
        dashboardLayout.setVerticalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(150, 150, 150))
        );

        MENU.add(dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 270, 40));

        pasien.setBackground(new java.awt.Color(155, 126, 189));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-patient-24.png"))); // NOI18N
        jLabel7.setPreferredSize(new java.awt.Dimension(25, 25));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Pasien");

        javax.swing.GroupLayout pasienLayout = new javax.swing.GroupLayout(pasien);
        pasien.setLayout(pasienLayout);
        pasienLayout.setHorizontalGroup(
            pasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pasienLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(122, 122, 122))
        );
        pasienLayout.setVerticalGroup(
            pasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pasienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(150, 150, 150))
        );

        MENU.add(pasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 270, 40));

        dokter.setBackground(new java.awt.Color(78, 48, 115));
        dokter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dokterMouseClicked(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-doctor-24.png"))); // NOI18N
        jLabel9.setPreferredSize(new java.awt.Dimension(25, 25));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Dokter");

        javax.swing.GroupLayout dokterLayout = new javax.swing.GroupLayout(dokter);
        dokter.setLayout(dokterLayout);
        dokterLayout.setHorizontalGroup(
            dokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dokterLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(122, 122, 122))
        );
        dokterLayout.setVerticalGroup(
            dokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dokterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(150, 150, 150))
        );

        MENU.add(dokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 270, 40));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Klinik Kartika Surabaya");
        MENU.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));
        MENU.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 82, 270, 10));

        getContentPane().add(MENU, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 690));

        Content.setBackground(new java.awt.Color(255, 255, 255));
        Content.setMinimumSize(new java.awt.Dimension(1000, 690));
        Content.setPreferredSize(new java.awt.Dimension(900, 500));
        Content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(244, 155, 171));
        Header.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Header.setPreferredSize(new java.awt.Dimension(150, 151));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Rekam Medis Pasien");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addContainerGap(651, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        Content.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 80));

        Mid.setBackground(new java.awt.Color(204, 204, 255));
        Mid.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detail Rekam Medis", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        Mid.setPreferredSize(new java.awt.Dimension(222, 500));
        Mid.setLayout(new java.awt.GridLayout(15, 2, 10, 10));

        Idtxt.setText("Nama Pasien");
        Mid.add(Idtxt);

        NamaPasienField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaPasienFieldActionPerformed(evt);
            }
        });
        Mid.add(NamaPasienField);

        Pasientxt.setText("Tanggal Lahir");
        Mid.add(Pasientxt);
        Mid.add(TglLahirField);

        jLabel12.setText("Jenis Kelamin");
        Mid.add(jLabel12);
        Mid.add(JenisKelaminField);

        jLabel14.setText("Alamat");
        Mid.add(jLabel14);
        Mid.add(AlamatField);

        jLabel15.setText("No Telepon");
        Mid.add(jLabel15);
        Mid.add(TelpField);

        jLabel16.setText("Email");
        Mid.add(jLabel16);
        Mid.add(EmailField);

        jLabel17.setText("Waktu Kunjungan");
        Mid.add(jLabel17);
        Mid.add(WaktuField);

        jLabel18.setText("Jenis Kunjungan");
        Mid.add(jLabel18);

        Combox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pemeriksaan Umum'", "'Pemeriksaan Spesialis'", "'Tindakan Minor'", "'Medical Check Up'", "'Vaksinasi" }));
        Mid.add(Combox);

        jLabel19.setText("Diagnosis");
        Mid.add(jLabel19);
        Mid.add(DiagnosisField);

        jLabel20.setText("Tindakan");
        Mid.add(jLabel20);
        Mid.add(TindakanField);

        jLabel21.setText("Obat Diberikan");
        Mid.add(jLabel21);
        Mid.add(ObatField);

        jLabel22.setText("Catatan");
        Mid.add(jLabel22);
        Mid.add(CatatanField);

        jLabel4.setText("Dokter");
        Mid.add(jLabel4);

        DokterBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Budi", "Ahmad", "Bakri" }));
        Mid.add(DokterBox);

        jLabel11.setText("Jadwal Kontrol Ulang");
        Mid.add(jLabel11);
        Mid.add(JadwalFild);

        Content.add(Mid, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 920, 550));

        Foot.setBackground(new java.awt.Color(204, 204, 255));

        Simpanbtn.setText("Simpan");
        Simpanbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanbtnActionPerformed(evt);
            }
        });

        ExportPdf.setText("Cetak");
        ExportPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportPdfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FootLayout = new javax.swing.GroupLayout(Foot);
        Foot.setLayout(FootLayout);
        FootLayout.setHorizontalGroup(
            FootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FootLayout.createSequentialGroup()
                .addContainerGap(733, Short.MAX_VALUE)
                .addComponent(Simpanbtn)
                .addGap(49, 49, 49)
                .addComponent(ExportPdf)
                .addContainerGap())
        );
        FootLayout.setVerticalGroup(
            FootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FootLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Simpanbtn)
                    .addComponent(ExportPdf))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        Content.add(Foot, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 920, 50));

        getContentPane().add(Content, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 920, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void farmasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_farmasiMouseClicked
        // TODO add your handling code here:
        new Farmasi().setVisible(true);
        dispose();
    }//GEN-LAST:event_farmasiMouseClicked

    private void dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseClicked
        // TODO add your handling code here:
        new Dashboard().setVisible(true);
        dispose();
    }//GEN-LAST:event_dashboardMouseClicked

    private void dokterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dokterMouseClicked
        // TODO add your handling code here:
        new Dokter().setVisible(true);
        dispose();
    }//GEN-LAST:event_dokterMouseClicked

    private void NamaPasienFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaPasienFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaPasienFieldActionPerformed

    private void SimpanbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanbtnActionPerformed
        // TODO add your handling code here:
//         try {
//        // Ambil data dari form
//        String diagnosa = DiagnosisField.getText();
//        String tindakan = TindakanField.getText();
//        String obat = ObatField.getText();
//        String catatan = CatatanField.getText();
//        String waktuKunjungan = WaktuField.getText();
//        String jenisKunjungan = Combox.getSelectedItem().toString();
//        String JadwalKontrol = JadwalFild.getText();
//        
//
//        // Buat objek Pasien
//        Pasien pasien = new Pasien();
//        pasien.setId(idPasien);  
//
//        // Buat dan isi model RekamMedis
//        Model.RekamMedis model = new Model.RekamMedis(pasien);
//        model.setDiagnosis(diagnosa);
//        model.setTindakan(tindakan);
//        model.setObat(obat);
//        model.setCatatan(catatan);
//        model.setWaktuKunjungan(waktuKunjungan);
//        model.setJenisKunjungan(jenisKunjungan);
//        model.setJadwalKontrol(JadwalKontrol);
//
//        // Simpan ke database
//        Connection conn = DbConnection.getConnection();
//        PreparedStatement ps = conn.prepareStatement("SELECT id FROM pasien WHERE nama = ?");
//        ps.setString(1, NamaPasienField.getText());
//        ResultSet rs = ps.executeQuery();
//        if (rs.next()) {
//                idPasien = rs.getInt("id");
//}
//
//        JOptionPane.showMessageDialog(this, "Data rekam medis berhasil disimpan.");
//
//    } catch (Exception e) {
//        JOptionPane.showMessageDialog(this, "Gagal menyimpan: " + e.getMessage());
//        e.printStackTrace();
//    }
    }//GEN-LAST:event_SimpanbtnActionPerformed

    private void ExportPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExportPdfActionPerformed
        // TODO add your handling code here:
        exportToPDF();
    }//GEN-LAST:event_ExportPdfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RekamMedis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RekamMedis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RekamMedis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RekamMedis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RekamMedis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AlamatField;
    private javax.swing.JTextField CatatanField;
    private javax.swing.JComboBox<String> Combox;
    private javax.swing.JPanel Content;
    private javax.swing.JTextField DiagnosisField;
    private javax.swing.JComboBox<String> DokterBox;
    private javax.swing.JTextField EmailField;
    private javax.swing.JButton ExportPdf;
    private javax.swing.JPanel Foot;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel Idtxt;
    private javax.swing.JTextField JadwalFild;
    private javax.swing.JTextField JenisKelaminField;
    private javax.swing.JPanel MENU;
    private javax.swing.JPanel Mid;
    private javax.swing.JTextField NamaPasienField;
    private javax.swing.JTextField ObatField;
    private javax.swing.JLabel Pasientxt;
    private javax.swing.JButton Simpanbtn;
    private javax.swing.JTextField TelpField;
    private javax.swing.JTextField TglLahirField;
    private javax.swing.JTextField TindakanField;
    private javax.swing.JTextField WaktuField;
    private javax.swing.JPanel dashboard;
    private javax.swing.JPanel dokter;
    private javax.swing.JPanel farmasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pasien;
    // End of variables declaration//GEN-END:variables

}