/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import Model.Kamar;
import DAO.KamarDAO;
import Util.DbConnection;
import java.sql.Connection;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asus
 */
public class Ruangan extends javax.swing.JFrame {

    /**
     * Creates new form Farmasi
     */
    public Ruangan() {
        initComponents();
        loadTable();
    }
    
    private void loadTable() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID");
    model.addColumn("Nomor Kamar");
    model.addColumn("Status");

    Connection conn = DbConnection.getConnection();
    KamarDAO dao = new KamarDAO(conn);
    List<Kamar> list = dao.getAll();

    for (Kamar k : list) {
        model.addRow(new Object[] {
            k.getId(),
            k.getNomorKamar(),
            k.getKeterangan()
        });
    }

    KamarTbl.setModel(model);
    KamarTbl.getColumnModel().getColumn(0).setMinWidth(0);
    KamarTbl.getColumnModel().getColumn(0).setMaxWidth(0);
}

    private void clearForm() {
    NoKamar.setText("");
    tersedia.setSelected(false);
    tidaktersedia.setSelected(false);
    selectedKamarId = -1;
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MENU = new javax.swing.JPanel();
        farmasi = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dashboard = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pasien = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dokter = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        DASHBOARD = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        formKamar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        NoKamar = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Upbtn = new javax.swing.JButton();
        tersedia = new javax.swing.JRadioButton();
        tidaktersedia = new javax.swing.JRadioButton();
        Kamar = new javax.swing.JPanel();
        KuotaKamar = new javax.swing.JScrollPane();
        KamarTbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MENU.setBackground(new java.awt.Color(127, 85, 177));
        MENU.setPreferredSize(new java.awt.Dimension(270, 450));
        MENU.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        farmasi.setBackground(new java.awt.Color(78, 48, 115));
        farmasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                farmasiMouseClicked(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-pharmacy-shop-24.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(25, 25));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Farmasi");

        javax.swing.GroupLayout farmasiLayout = new javax.swing.GroupLayout(farmasi);
        farmasi.setLayout(farmasiLayout);
        farmasiLayout.setHorizontalGroup(
            farmasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(farmasiLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(122, 122, 122))
        );
        farmasiLayout.setVerticalGroup(
            farmasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(farmasiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(farmasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(150, 150, 150))
        );

        MENU.add(farmasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 270, 40));

        dashboard.setBackground(new java.awt.Color(155, 126, 189));
        dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardMouseClicked(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-home-24.png"))); // NOI18N
        jLabel5.setPreferredSize(new java.awt.Dimension(25, 25));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Dashboard");

        javax.swing.GroupLayout dashboardLayout = new javax.swing.GroupLayout(dashboard);
        dashboard.setLayout(dashboardLayout);
        dashboardLayout.setHorizontalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(122, 122, 122))
        );
        dashboardLayout.setVerticalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(150, 150, 150))
        );

        MENU.add(dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 270, 40));

        pasien.setBackground(new java.awt.Color(78, 48, 115));
        pasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pasienMouseClicked(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-patient-24.png"))); // NOI18N
        jLabel7.setPreferredSize(new java.awt.Dimension(25, 25));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Pasien");

        javax.swing.GroupLayout pasienLayout = new javax.swing.GroupLayout(pasien);
        pasien.setLayout(pasienLayout);
        pasienLayout.setHorizontalGroup(
            pasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pasienLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(122, 122, 122))
        );
        pasienLayout.setVerticalGroup(
            pasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pasienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(150, 150, 150))
        );

        MENU.add(pasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 270, 40));

        dokter.setBackground(new java.awt.Color(78, 48, 115));
        dokter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dokterMouseClicked(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-doctor-24.png"))); // NOI18N
        jLabel9.setPreferredSize(new java.awt.Dimension(25, 25));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Dokter");

        javax.swing.GroupLayout dokterLayout = new javax.swing.GroupLayout(dokter);
        dokter.setLayout(dokterLayout);
        dokterLayout.setHorizontalGroup(
            dokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dokterLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(122, 122, 122))
        );
        dokterLayout.setVerticalGroup(
            dokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dokterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dokterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(150, 150, 150))
        );

        MENU.add(dokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 270, 40));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Klinik Kartika Surabaya");
        MENU.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));
        MENU.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 82, 270, 10));

        getContentPane().add(MENU, java.awt.BorderLayout.LINE_START);

        DASHBOARD.setBackground(new java.awt.Color(255, 255, 255));
        DASHBOARD.setAlignmentX(5.0F);
        DASHBOARD.setPreferredSize(new java.awt.Dimension(900, 450));
        DASHBOARD.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(244, 155, 171));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Kuota Kamar Rawat Inap");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel11)
                .addContainerGap(308, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel11)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        DASHBOARD.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, -1));

        formKamar.setBackground(new java.awt.Color(127, 85, 177));
        formKamar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kuota Kamar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        formKamar.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nomor Kamar");

        NoKamar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        NoKamar.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Status");

        Upbtn.setBackground(new java.awt.Color(255, 255, 255));
        Upbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Upbtn.setForeground(new java.awt.Color(127, 85, 177));
        Upbtn.setText("Update");
        Upbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpbtnActionPerformed(evt);
            }
        });

        tersedia.setBackground(new java.awt.Color(255, 255, 255));
        tersedia.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tersedia.setText("Tersedia");

        tidaktersedia.setBackground(new java.awt.Color(255, 255, 255));
        tidaktersedia.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tidaktersedia.setText("Tidak Tersedia");

        javax.swing.GroupLayout formKamarLayout = new javax.swing.GroupLayout(formKamar);
        formKamar.setLayout(formKamarLayout);
        formKamarLayout.setHorizontalGroup(
            formKamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formKamarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formKamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formKamarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Upbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formKamarLayout.createSequentialGroup()
                        .addGroup(formKamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel12))
                        .addGap(29, 29, 29)
                        .addGroup(formKamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NoKamar, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                            .addGroup(formKamarLayout.createSequentialGroup()
                                .addComponent(tersedia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(tidaktersedia, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        formKamarLayout.setVerticalGroup(
            formKamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formKamarLayout.createSequentialGroup()
                .addGroup(formKamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NoKamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(formKamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(formKamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tersedia)
                        .addComponent(tidaktersedia)))
                .addGap(17, 17, 17)
                .addComponent(Upbtn)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        DASHBOARD.add(formKamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 550, 180));

        Kamar.setBackground(new java.awt.Color(127, 85, 177));
        Kamar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kuota Kamar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        Kamar.setForeground(new java.awt.Color(255, 255, 255));
        Kamar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Kamar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        KamarTbl.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        KamarTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nomor Kamar", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        KamarTbl.setGridColor(new java.awt.Color(127, 85, 177));
        KamarTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KamarTblMouseClicked(evt);
            }
        });
        KuotaKamar.setViewportView(KamarTbl);

        Kamar.add(KuotaKamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 530, 130));

        DASHBOARD.add(Kamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 550, 170));

        getContentPane().add(DASHBOARD, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseClicked
        // TODO add your handling code here:
        new Dashboard().setVisible(true);
            dispose();
    }//GEN-LAST:event_dashboardMouseClicked

    private void pasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pasienMouseClicked
        // TODO add your handling code here:
        new DataPasien().setVisible(true);
            dispose();
    }//GEN-LAST:event_pasienMouseClicked

    private void dokterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dokterMouseClicked
        // TODO add your handling code here:
        new Dokter().setVisible(true);
            dispose();
    }//GEN-LAST:event_dokterMouseClicked

    private void farmasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_farmasiMouseClicked
        // TODO add your handling code here:
        new Farmasi().setVisible(true);
            dispose();
    }//GEN-LAST:event_farmasiMouseClicked

    private void KamarTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KamarTblMouseClicked
        // TODO add your handling code here:
        int row = KamarTbl.getSelectedRow();
        if (row != -1) {
        selectedKamarId = Integer.parseInt(KamarTbl.getValueAt(row, 0).toString());
        NoKamar.setText(KamarTbl.getValueAt(row, 1).toString());
        String status = KamarTbl.getValueAt(row, 2).toString();

        if (status.equals("Tersedia")) {
            tersedia.setSelected(true);
        } else {
            tidaktersedia.setSelected(true);
        }
    }
    }//GEN-LAST:event_KamarTblMouseClicked

    private void UpbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpbtnActionPerformed
        // TODO add your handling code here:
        int nomorKamar = Integer.parseInt(NoKamar.getText());
        String keterangan = tersedia.isSelected() ? "Tersedia" : "Tidak Tersedia";

        Connection conn = DbConnection.getConnection();
        KamarDAO dao = new KamarDAO(conn);

        if (selectedKamarId != -1) {
            Kamar kamar = new Kamar(selectedKamarId, nomorKamar, keterangan);
            dao.update(kamar);
            JOptionPane.showMessageDialog(this, "Data kamar diperbarui!");
        } else {
            Kamar kamar = new Kamar(nomorKamar, keterangan);
            dao.insert(kamar);
            JOptionPane.showMessageDialog(this, "Kamar baru ditambahkan!");
        }

        clearForm();
        loadTable();
    }//GEN-LAST:event_UpbtnActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ruangan().setVisible(true);
            }
        });
    }

    private int selectedKamarId = -1;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DASHBOARD;
    private javax.swing.JPanel Kamar;
    private javax.swing.JTable KamarTbl;
    private javax.swing.JScrollPane KuotaKamar;
    private javax.swing.JPanel MENU;
    private javax.swing.JTextField NoKamar;
    private javax.swing.JButton Upbtn;
    private javax.swing.JPanel dashboard;
    private javax.swing.JPanel dokter;
    private javax.swing.JPanel farmasi;
    private javax.swing.JPanel formKamar;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pasien;
    private javax.swing.JRadioButton tersedia;
    private javax.swing.JRadioButton tidaktersedia;
    // End of variables declaration//GEN-END:variables
}
