/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

/**
 *
 * @author Lenovo
 */
public class Test extends javax.swing.JFrame {

    /**
     * Creates new form Test
     */
    public Test() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        IdPasienlb = new javax.swing.JLabel();
        Namalb = new javax.swing.JLabel();
        TanggalLB = new javax.swing.JLabel();
        Jenislb = new javax.swing.JLabel();
        Alamatlb = new javax.swing.JLabel();
        NoTelplb = new javax.swing.JLabel();
        EmailLb = new javax.swing.JLabel();
        Mid = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        TanggalKunjugan = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        JenisKunjuganbox = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Diagnosistxt = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        Tindakantxt = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel24 = new javax.swing.JLabel();
        Obatfield = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        Jadwalfield = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Header.setBackground(new java.awt.Color(244, 155, 171));
        Header.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informasi Pasien", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 24))); // NOI18N
        Header.setForeground(new java.awt.Color(255, 255, 255));
        Header.setAlignmentX(6.0F);
        Header.setAlignmentY(6.0F);
        Header.setPreferredSize(new java.awt.Dimension(700, 180));
        Header.setLayout(new java.awt.GridLayout(2, 4, 10, 0));

        IdPasienlb.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        IdPasienlb.setForeground(new java.awt.Color(255, 255, 255));
        IdPasienlb.setText("ID Pasien        :");
        Header.add(IdPasienlb);

        Namalb.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Namalb.setForeground(new java.awt.Color(255, 255, 255));
        Namalb.setText("Nama               :");
        Header.add(Namalb);

        TanggalLB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TanggalLB.setForeground(new java.awt.Color(255, 255, 255));
        TanggalLB.setText("Tanggal Lahir   :");
        Header.add(TanggalLB);

        Jenislb.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Jenislb.setForeground(new java.awt.Color(255, 255, 255));
        Jenislb.setText("Jenis Kelamin  :");
        Header.add(Jenislb);

        Alamatlb.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Alamatlb.setForeground(new java.awt.Color(255, 255, 255));
        Alamatlb.setText(" Alamat          :");
        Header.add(Alamatlb);

        NoTelplb.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        NoTelplb.setForeground(new java.awt.Color(255, 255, 255));
        NoTelplb.setText("No Telp           :");
        Header.add(NoTelplb);

        EmailLb.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EmailLb.setForeground(new java.awt.Color(255, 255, 255));
        EmailLb.setText("Email                  :");
        Header.add(EmailLb);

        Mid.setBackground(new java.awt.Color(127, 85, 177));
        Mid.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tambah Rekam Medis", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        Mid.setForeground(new java.awt.Color(255, 255, 255));
        Mid.setAlignmentX(6.0F);
        Mid.setAlignmentY(6.0F);
        Mid.setPreferredSize(new java.awt.Dimension(700, 250));
        Mid.setLayout(new java.awt.GridLayout(7, 2, 10, 10));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Tanggal Kunjunagan");
        Mid.add(jLabel19);

        TanggalKunjugan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanggalKunjuganActionPerformed(evt);
            }
        });
        Mid.add(TanggalKunjugan);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Jenis Kunjungan");
        Mid.add(jLabel11);

        JenisKunjuganbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pemeriksaan Umum", "Pemeriksaan Spesialis", "Tindakan Minor", "Medical Check Up", "Vaksinasi" }));
        Mid.add(JenisKunjuganbox);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Diagnosis");
        Mid.add(jLabel16);

        Diagnosistxt.setColumns(20);
        Diagnosistxt.setRows(5);
        jScrollPane1.setViewportView(Diagnosistxt);

        Mid.add(jScrollPane1);

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Tindakan");
        Mid.add(jLabel23);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        Tindakantxt.setViewportView(jTextArea2);

        Mid.add(Tindakantxt);

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Obat Diberikan");
        Mid.add(jLabel24);
        Mid.add(Obatfield);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Jadwal Kontrol Ulang");
        Mid.add(jLabel25);
        Mid.add(Jadwalfield);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Mid, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 263, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Mid, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                    .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 226, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TanggalKunjuganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TanggalKunjuganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TanggalKunjuganActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alamatlb;
    private javax.swing.JTextArea Diagnosistxt;
    private javax.swing.JLabel EmailLb;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel IdPasienlb;
    private javax.swing.JTextField Jadwalfield;
    private javax.swing.JComboBox<String> JenisKunjuganbox;
    private javax.swing.JLabel Jenislb;
    private javax.swing.JPanel Mid;
    private javax.swing.JLabel Namalb;
    private javax.swing.JLabel NoTelplb;
    private javax.swing.JTextField Obatfield;
    private javax.swing.JTextField TanggalKunjugan;
    private javax.swing.JLabel TanggalLB;
    private javax.swing.JScrollPane Tindakantxt;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
